# Basic
name:               "Axel Hodler"

# URL
baseurl:            ""
permalink:          pretty

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "Blog"
    href:           "/"
  - name:           "Books"
    href:           "/books"
  - name:           "About"
    href:           "/about"

# Sass
sass:
  style:            :compressed

collections:
  books:
    output: true


# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
